version: "3"

services:
#  db:
#    image: mysql:8.0
#    ports:
#      - 3307:3306
#    environment:
  app:
    build:
      context: .
      dockerfile: ./docker/python/DockerFile
    ports:
      - 8000:5000
    volumes:
      - .:/app
